#!/usr/bin/env ruby

require 'redis'

r = Redis.new
r.flushdb

def random_reason
  ["billing_record", "response_code", "sql_injection", "manual"].sample
end

def random_whitelist
  ["manual", "nat", "carrier"].sample
end

25.times do |i|
  r.set("1.1.1.#{i}:repsheet:ip:blacklisted", random_reason)
end

25.times do |i|
  r.set("2.2.2.#{i}:repsheet:ip:whitelisted", random_whitelist)
end

25.times do |i|
  r.set("3.3.3.#{i}:repsheet:ip:marked", random_reason)
end

